/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Mehdi Shahsavan (https://sketchfab.com/ahmagh2e)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/flash-light-17mb-ed6f710f094641abba62bcf30e9b3003
Title: Flash Light - 17MB
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.base_base_0.geometry}
          material={materials.base}
          position={[0, 37.169, 92.269]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.glass_glass_0.geometry}
          material={materials.glass}
          position={[0, 0, -323.083]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
