/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: syasya.affandi (https://sketchfab.com/syasya.affandi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/prism-7e70214d0cae4360bd3fbe6c108f3674
Title: Prism
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[11.583, 0, -1.611]} rotation={[-Math.PI / 2, 0, -0.475]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[0.19, 0.078, 46.036]}
            rotation={[-Math.PI / 2, -1.1, 0]}
            scale={[1, 1, 1.704]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Line013_09_-_Default_0'].geometry}
              material={materials['09_-_Default']}
              position={[8.942, 0, 0]}
            />
          </group>
          <group
            position={[18.176, 0.078, 46.058]}
            rotation={[-Math.PI / 2, 1.104, 0]}
            scale={[1, 1, 1.704]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Line014_09_-_Default_0'].geometry}
              material={materials['09_-_Default']}
              position={[-9.045, 0, 0]}
            />
          </group>
          <group position={[18.08, 0.005, 0.067]} rotation={[-Math.PI / 2, 1.103, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Line015_09_-_Default_0'].geometry}
              material={materials['09_-_Default']}
              position={[-8.948, 0, 0]}
            />
          </group>
          <group position={[0.259, 0.005, 0.032]} rotation={[-Math.PI / 2, -1.099, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Line016_09_-_Default_0'].geometry}
              material={materials['09_-_Default']}
              position={[8.873, 0, 0]}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Prism001_07_-_Default_0'].geometry}
            material={materials['07_-_Default']}
            scale={[0.351, 0.351, 1.996]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Line001_09_-_Default_0'].geometry}
            material={materials['09_-_Default']}
            position={[-5.156, 0.068, 22.937]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[1.238, 1, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Line002_09_-_Default_0'].geometry}
            material={materials['09_-_Default']}
            position={[14.006, 0.049, 22.937]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Line003_09_-_Default_0'].geometry}
            material={materials['09_-_Default']}
            position={[9.132, 0.127, 46.118]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[1, 1, 1.704]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Line004_09_-_Default_0'].geometry}
            material={materials['09_-_Default']}
            position={[9.132, 0.166, 0.174]}
            rotation={[-Math.PI / 2, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Line009_02_-_Default_0'].geometry}
            material={materials['02_-_Default']}
            position={[9.63, 4.039, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Line011_02_-_Default_0'].geometry}
            material={materials['02_-_Default']}
            position={[9.514, 4.039, 46.217]}
            scale={[0.744, 1, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.TextPlus001__0.geometry}
            material={materials.TextPlus001__0}
            position={[-1.522, -0.825, 46.247]}
            scale={0.099}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.TextPlus002__0.geometry}
            material={materials.TextPlus001__0}
            position={[19.735, -0.825, 46.247]}
            scale={0.099}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.TextPlus003__0.geometry}
            material={materials.TextPlus001__0}
            position={[9.356, -2.126, 46.247]}
            scale={0.099}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.TextPlus004__0.geometry}
            material={materials.TextPlus001__0}
            position={[9.356, 18.59, 46.247]}
            scale={0.099}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.TextPlus005__0.geometry}
            material={materials.TextPlus001__0}
            position={[-1.074, -0.899, -0.006]}
            scale={0.099}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.TextPlus006__0.geometry}
            material={materials.TextPlus001__0}
            position={[19.362, -1.049, -0.006]}
            scale={0.099}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.TextPlus007__0.geometry}
            material={materials.TextPlus001__0}
            position={[9.356, -2.126, -0.006]}
            scale={0.099}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.TextPlus008__0.geometry}
            material={materials.TextPlus001__0}
            position={[9.356, 18.59, -0.006]}
            scale={0.099}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['Plane001_03_-_Default_0'].geometry}
            material={materials['03_-_Default']}
            position={[9.138, 9.114, 23.146]}
            rotation={[-Math.PI / 2, 1.563, 0]}
            scale={[0.856, 2.631, 1]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
