/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Alex Bes (https://sketchfab.com/alexbescg)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nails-01b4745c45ac480d99d51879165cd247
Title: Nails
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.nails_model_nails_mat_0.geometry}
        material={materials.nails_mat}
      />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
