/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: famousandfaded (https://sketchfab.com/famousandfaded)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/alnico-rectangular-bar-magnet-d6764405fb174b4b82063a56ffd3d63d
Title: Alnico rectangular bar magnet
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.matmaterial_magnet}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
