/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: 3dhdscan (https://sketchfab.com/3dhdscan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wood-stick-01-35c2a83f89da49b58d41dea9ca5ed330
Title: Wood stick 01
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0.703, 1.479, -2.182]} rotation={[-Math.PI, Math.PI / 2, 0]} scale={0.011}>
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wood_stick_01_wood_stick_01_0.geometry}
            material={materials.wood_stick_01}
            position={[-0.23, -2.413, 0.934]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
